### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by xico42** [JesseFarebro/deadbeef-librarybrowser#1]
As you suggest in the README, we should
./autogen.sh
./configure
make

autogen.sh gives the following errors:
required files not found:
./NEWS
./README
./AUTHORS
./Changelog

And configure:
config.status error: cannot find input file: 'Makefile.in'

So make has no targets.

I have deadbeef and gtk2 headers in my path, i have already compiled the deadbeef file browser plugin as well.

**Comment by JesseFarebro** [comment]
Sorry about that, didn't catch it before uploading. Just fixed it in the
last commit.
